#ifndef POPWILHEADER_H
#define POPWILHEADER_H

#include "stdio.h"
#include <QObject>
#include <string>
#include <QMainWindow>
#include <QDialog>
#include <QDateTime>
#include <QTimer>
#include <QLabel>
#include <QScrollbar>
#include "qchartviewer.h"
#include "qdoublebufferedqueue.h"
#include "bdaqctrl.h"
#include "configuredialog.h"
#include "performancetimer.h"
#include "QStandardItemModel"
#include "qstring.h"
#include "logger.h"
#include "aiinstant.h"
#include "aoinstant.h"
#include <QCloseEvent>
#include <QApplication>
#include <QButtonGroup>
#include <QIcon>
#include <QPushButton>
#include <QComboBox>
#include <QFileDialog>
#include "chartdir.h"
#include <math.h>
#include <vector>
#include <sstream>
#include "qdebug.h"
#include "QTime"
#include "qmessagebox.h"
#include "aboutform.h"
#include "qdesktopservices.h"
#include <QProcess>
#include "Enc7480.h"
#include "qmath.h"
#include "inihelper.h"
#include "ctrldialog.h"
#include "rbf.h"
#include "systemsettings.h"
#include "QStandardItem"
#include "mathtool.h"
//#include "QtXlsx"
#include "signalprocess.h"
#include "constvar.h"
#include <QTextCodec>
#include <QTextStream>
#include "doinstant.h"
#include "aistreaming.h"
#include "mychartviewer.h"
#include "staticpositioncontroller.h"
#include <vector>
#include "AVGFilter.h"
#include "ButtorFilter.h"
#include "PIDController.h"
#include "TVController.h"
#include "PID3Controller.h"
#include "sinesweepmodule.h"
#include "Oscilator.h"
#include <QListWidgetItem>
#include "DisplayBuffer.h"
#include "DisplayBufferForm.h"


#endif // POPWILHEADER_H
